train:
  data_root: "Images"
  image_size: 224
  batch_size: 32
  num_workers: 2
  num_classes: 2
  class_names: ["Stroke", "Normal"]
  epochs: 50
  lr: 0.0005
  weight_decay: 0.0001
  early_stopping_patience: 12
  val_split: 0.2
  seed: 42
  checkpoint_dir: "checkpoints"
  csv_file: null

federated:
  server_address: "127.0.0.1:8080"
  num_clients: 3
  rounds: 10
  fraction_fit: 1.0
  fraction_eval: 1.0
